### ISSUE TITLE
Crash on leatest BL2 include all DLC

### ISSUE THREAD

**Issue by FreddeITsupport98** [xcier/Borderlands#1]
![hybrid save loading and this accours](https://user-images.githubusercontent.com/38165242/83224592-0f211900-a17e-11ea-8e51-ffe7db6bdd6f.png)

Hi, love your work what you made. But i have question about hybrid saves. Every time i load hybrid save, it crashes the game when i click on "continue." Any tips?

I used the latest save that you provided in GitHub.
Sorry i missed something.

Sincere
Yours truly Freddy

**Comment by Azazel131** [comment]
@FreddeITsupport98 did you try and reinstall your game?

**Comment by FreddeITsupport98** [comment]
YES IT RESOLVED.
